spring:
  data:
    mongodb:
      database: ux-analytics
      uri: mongodb+srv://uxanalytics:d0902Vtx1wFY92xK@ux-analytics-mongo-clus.fogfryi.mongodb.net/?retryWrites=true&w=majority&appName=ux-analytics-mongo-cluster
  docker:
    compose:
      enabled: false

expiry:
  user-journeys:
    stale-threshold-in-minutes: 5

logging:
  level:
    com.dragutin.uxanalytics: DEBUG
    org.springframework.data: WARN